#!/bin/bash
#SBATCH --output=/gpfs/home6/ekoornstra/logs/slurm-%j.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=e.koornstra@erasmusmc.nl
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=32

module load 2022
module load R/4.2.1-foss-2022a
export R_LIBS=/gpfs/home6/ekoornstra/rpackages:$R_LIBS


echo "running for hNSC raqtls"
inpath="/home/ekoornstra/raqtls/freeze7/hnsc_no_downsampling_snp-permutation_freeze7_wilc-raqtls_04042024.txt"
outpath="/home/ekoornstra/raqtls/freeze7/annotations/hnsc_no_downsampling_snp-permutation_freeze7_wilc-raqtls_04042024_ANNOTATED.txt"

Rscript add_all_genomic_features_28022024.R ${inpath} ${outpath}
