#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=32
#SBATCH --mail-type=ALL
#SBATCH --mail-user=e.koornstra@erasmusmc.nl
#SBATCH --output=/home/ekoornstra/logs/slurm-%j.out


export R_LIBS=$HOME/rpackages:$R_LIBS

# paths
set_path="/gpfs/home6/ekoornstra/sure_data/freeze7/pvalue.freeze7.snp-permutation.04042024.txt.gz"
setname="all_sure"
info_path="/gpfs/home6/ekoornstra/surexgwas/freeze7/distance-to-lead/infofile_08042024.txt"
out_path="/gpfs/home6/ekoornstra/surexgwas/freeze7/distance-to-lead/all_sure/"

# run script
Rscript 01_distance_to_lead_snp.R ${set_path} ${setname} ${info_path} ${out_path}

# paths
#set_path2="/gpfs/home6/ekoornstra/raqtls/freeze7/hnsc_freeze7_raqtl_sampled-matched-controls_16042024.txt"
#setname2="sampled_matched_controls"
#info_path2="/gpfs/home6/ekoornstra/surexgwas/freeze7/distance-to-lead/infofile_08042024.txt"
#out_path2="/gpfs/home6/ekoornstra/surexgwas/freeze7/distance-to-lead/sampled_matched_controls/"

# run script
#Rscript 01_distance_to_lead_snp.R ${set_path2} ${setname2} ${info_path2} ${out_path2}

