#!/bin/bash
#SBATCH --output=/gpfs/home6/ekoornstra/surexgwas/freeze7/finemapping/SCZ/logs/scz_run-%j.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=e.koornstra@erasmusmc.nl
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --time=13:00:00
#SBATCH --cpus-per-task=16

# paths
path="/gpfs/home6/ekoornstra/surexgwas/freeze7/finemapping/SCZ/"
inputlist="SCZ_processed-loci_EK250722.txt"
filepath="files/running-files/"
outpath="files/results/"
Zhead="Zscore"
LDfilesuffix="ld"

# annotations
annotlist="WeakEnhancer_Hoffman.bed,UTR_5_UCSC.bed,UTR_3_UCSC.bed,TSS_Hoffman.bed,Transcribed_Hoffman.bed,TFBS_ENCODE.bed,SuperEnhancer_Hnisz.bed,Repressed_Hoffman.bed,PromoterFlanking_Hoffman.bed,Promoter_UCSC.bed,Intron_UCSC.bed,H3K27ac_PGC2.bed,H3K27ac_Hnisz.bed,H3K9ac_peaks_Trynka.bed,H3K4me3_peaks_Trynka.bed,H3K4me1_peaks_Trynka.bed,FetalDHS_Trynka.bed,Enhancer_Hoffman.bed,Enhancer_Andersson.bed,DHS_peaks_Trynka.bed,DGF_ENCODE.bed,CTCF_Hoffman.bed,Conserved_LindbladToh.bed,Coding_UCSC.bed"

# load packages
echo "reloading modules"
module purge
module load 2023
module load SciPy-bundle/2023.07-gfbf-2023a

# run paintor
echo "running paintor for all loci"
cd /gpfs/home6/ekoornstra/opt/PAINTOR_V3.0/

./PAINTOR -input ${path}${inputlist} \
  -in ${path}${filepath} \
  -out ${path}${outpath} \
  -Zhead Zscore -LDname ld -mcmc \
  -Gname Enrich.ldsc -Lname BF.ldsc \
  -annotations ${annotlist}

