#!/bin/bash
#SBATCH --output=/home/ekoornstra/logs/slurm-%j.out
#SBATCH --mail-type=END
#SBATCH --mail-user=e.koornstra@erasmusmc.nl
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=32

## THIS FILE FILE CAN BE USED TO GENERATE YOUR OWN WEIGHTS FILES ##

# load packages
echo loading modules
module purge
module load 2021
module load Anaconda3/2021.05

# change directory
echo changing to ldsc directory
cd ~/opt/ldsc/

# create an environment with ldsc dependencies
conda env create --file environment.yml

echo activating ldsc environment
source activate ldsc

# run ldsc partitioned ld score calculation in parallel for the 22 autosomes
echo reloading modules
module purge
module load 2021
module load Python/2.7.18-GCCcore-10.3.0-bare

echo running ldsc univariate

# for the weights file
for i in {1..22}
do
python2 ~/opt/ldsc/ldsc.py --l2 --bfile ~/ldsc/plinkfiles/1000G_EUR_Phase3_plink/1000G.EUR.QC.$i \
  --ld-wind-cm 1 \
  --out ~/ldsc/weights_1kg_phase3_allsnps/weights.$i \
  --extract ~/ldsc/regression.snplist &
done

wait
echo "all done"




