#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=32
#SBATCH --mail-type=ALL
#SBATCH --mail-user=e.koornstra@erasmusmc.nl
#SBATCH --output=/home/ekoornstra/logs/slurm-%j.out

## RUN THIS TO MAKE YOUR ANNOTATION FILES ##
# paths are within the scripts!!

export R_LIBS=$HOME/rpackages:$R_LIBS


#Rscript annotfile_prep_continuous.R
#Rscript annotfile_prep_binary.R

Rscript annotfile_prep_binary_hnsc.R
#Rscript annotfile_prep_tf_eva.R
