#!/bin/bash
#SBATCH --output=/home/ekoornstra/logs/slurm-%j.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=e.koornstra@erasmusmc.nl
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --time=0:30:00
#SBATCH --cpus-per-task=32
#SBATCH --partition=rome

## DETERMINE THE PARTITIONED HERITABILITY ##
## before running this script you should have already calculated ld scores

# FILES
sumstat="astle2016_rbc_N172952_narrow_form.sumstats.gz"
output="rbc-full_astle2016"
sumstat2="astle2016_wbc_N172435_narrow_form.sumstats.gz"
output2="wbc-full_astle2016"

# output file format to keep it consistent: phenotype-authoryear_1kg-approach_nosure/binary/cont_heritability_freeze4

# no hapmap3 filter on sumstats, ld file filtered on sure snps, and weights from all 1kg phase3 snps
refld_binary="/gpfs/home6/ekoornstra/ldsc/freeze7/annotation_ld/1000G_Phase3_baselineLD_v2.2_nohm3filter_hnsc/baselineLD.v2.2.sure.hnsc."
outpath="/gpfs/home6/ekoornstra/ldsc/freeze7/heritability_results/"

path="/gpfs/home6/ekoornstra/ldsc/freeze7/"
weights="weights/weights_1kg_phase3_allsnps/weights."
frqfile="1000G_Phase3_frq/1000G.EUR.QC."

# load packages
echo loading modules
module purge
module load 2021
module load Anaconda3/2021.05

# change to ldsc directory
echo changing to ldsc directory
cd ~/opt/ldsc/

# create an environment with ldsc dependencies
echo ldsc environment
conda env create --file environment.yml
source activate ldsc

# reload modules
echo reloading modules
module purge
module load 2021
module load Python/2.7.18-GCCcore-10.3.0-bare

# run ldsc partitioned heritability
echo running partitioned heritability with hnsc sure data
python2 ldsc.py --h2 ${path}sumstats/${sumstat} \
  --ref-ld-chr ${refld_binary} \
  --w-ld-chr ${path}${weights} \
  --overlap-annot \
  --frqfile-chr ${path}${frqfile} \
  --print-coefficients \
  --print-delete-vals \
  --out ${outpath}${output}_hnsc_heritability_freeze7


echo running partitioned heritability with hnsc sure data second phenotypes
python2 ldsc.py --h2 ${path}sumstats/${sumstat2} \
  --ref-ld-chr ${refld_binary} \
  --w-ld-chr ${path}${weights} \
  --overlap-annot \
  --frqfile-chr ${path}${frqfile} \
  --print-coefficients \
  --print-delete-vals \
  --out ${outpath}${output2}_hnsc_heritability_freeze7


