#!/bin/bash
#SBATCH --output=/home/ekoornstra/logs/slurm-%j.out
#SBATCH --mail-type=END
#SBATCH --mail-user=e.koornstra@erasmusmc.nl
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=32

## before running this script you should have already calculated ld scores

# FILES
pheno="uc-delange2017"
quantile=10
path="/gpfs/home6/ekoornstra/ldsc/FINAL_FILES/1kg_approach/heritability_results/continuous/"
basename="_1kg-approach_continuous_heritability_freeze4"
annot="/gpfs/home6/ekoornstra/ldsc/FINAL_FILES/1kg_approach/1000G_Phase3_baselineLD_v2.2_continuous/baselineLD.v2.2.sure.continuous."
frq="/gpfs/home6/ekoornstra/ldsc/FINAL_FILES/1000G_Phase3_frq/1000G.EUR.QC."
header_hnpc="hnpc_ziw_neglog10p"
header_hepg2="hepg2_neglog10p"
header_k562="k562_neglog10p"

# load packages
echo loading modules
module purge
module load 2021
module load Anaconda3/2021.05

# change to ldsc directory
echo changing to ldsc directory
cd ~/opt/ldsc/

# create an environment with ldsc dependencies
echo ldsc environment
conda env create --file environment.yml
source activate ldsc

# reload modules
echo reloading modules
module purge
module load 2021
module load R/4.1.0-foss-2021a

# run perl quantile script
echo running perl quantile script

perl ~/opt/ldsc/ContinuousAnnotations/quantile_M.pl --ref-annot-chr ${annot} \
  --frqfile-chr ${frq} \
  --annot-header ${header_hnpc} \
  --nb-quantile ${quantile} --maf 0.05 \
  --out ${path}quantile_results/${header_hnpc}_${pheno}${basename}.q${quantile}.M

perl ~/opt/ldsc/ContinuousAnnotations/quantile_M.pl --ref-annot-chr ${annot} \
  --frqfile-chr ${frq} \
  --annot-header ${header_k562} \
  --nb-quantile ${quantile} --maf 0.05 \
  --out ${path}quantile_results/${header_k562}_${pheno}${basename}.q${quantile}.M

perl ~/opt/ldsc/ContinuousAnnotations/quantile_M.pl --ref-annot-chr ${annot} \
  --frqfile-chr ${frq} \
  --annot-header ${header_hepg2} \
  --nb-quantile ${quantile} --maf 0.05 \
  --out ${path}quantile_results/${header_hepg2}_${pheno}${basename}.q${quantile}.M

# run heritability per quantile
echo determining heritability per quantile

# needs quantile file, ldsc results, and name of output file
Rscript ~/opt/ldsc/ContinuousAnnotations/quantile_h2g.r ${path}quantile_results/${header_hnpc}_${pheno}${basename}.q${quantile}.M ${path}${pheno}${basename} ${path}quantile_results/${header_hnpc}_${pheno}${basename}.q${quantile}.txt

Rscript ~/opt/ldsc/ContinuousAnnotations/quantile_h2g.r ${path}quantile_results/${header_k562}_${pheno}${basename}.q${quantile}.M ${path}${pheno}${basename} ${path}quantile_results/${header_k562}_${pheno}${basename}.q${quantile}.txt

Rscript ~/opt/ldsc/ContinuousAnnotations/quantile_h2g.r ${path}quantile_results/${header_hepg2}_${pheno}${basename}.q${quantile}.M ${path}${pheno}${basename} ${path}quantile_results/${header_hepg2}_${pheno}${basename}.q${quantile}.txt


